# Generated by Django 4.1.9 on 2023-12-23 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("otp_key", models.CharField(max_length=6)),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
